### ISSUE TITLE
Waiting time - Occupation Times 

### ISSUE THREAD

**Issue by 11michalis11** [11michalis11/AmbulanceDecisionGame#5]
Investigate merging, aggregating states. Also look at the Lumpability of states and maybe check out https://core.ac.uk/download/pdf/81156854.pdf

**Comment by 11michalis11** [comment]
Read about occupation times:
- https://www.demogr.mpg.de/papers/working/wp-2017-017.pdf
- https://hal.inria.fr/inria-00072852/document
- https://www.jstor.org/stable/1425817?seq=1
- https://projecteuclid.org/euclid.ejp/1464818494

**Comment by drvinceknight** [comment]
Here's the notes from our discussion on 2020-05-05

[2020-05-05-Note-12-09.pdf](https://github.com/11michalis11/AmbulanceDecisionGame/files/4580339/2020-05-05-Note-12-09.pdf)
